services:
  server:
    container_name: palmox_server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8081:5000"
    volumes:
      - ../src/server:/home/pythonuser/app
  db:
    container_name: palmox_db
    build: ./db
    env_file: ./db/.env
  db_admin:
    container_name: palmox_db_admin
    build: ./db-admin
    env_file: ./db-admin/.env
    ports:
      - "8082:80"
  db_messenger:
    container_name: palmox_db_messenger
    build: ./db-messenger
    secrets:
      - redis_client_password
      - redis_server_password
secrets:
  redis_client_password:
    file: ./secrets/redis_client_password.secret
  redis_server_password:
    file: ./secrets/redis_server_password.secret