services:
  server:
    container_name: palmox_server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8081:5000"
    volumes:
      - ../src/server:/home/pythonuser/app
    networks:
      - public
      - internal
  db:
    container_name: palmox_db
    build:
      context: ./db
      dockerfile: Dockerfile.dev
    env_file: ./db/.env
    networks:
      - internal
  db_admin:
    container_name: palmox_db_admin
    build:
      context: ./db-admin
      dockerfile: Dockerfile.dev
    env_file: ./db-admin/.env
    ports:
      - "8082:80"
    networks:
      - public
      - internal
  redis:
    container_name: palmox_redis
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    env_file: ./redis/.env
    networks:
      - internal

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true